### PR TITLE
using . instead of .data$.

### PR DESCRIPTION
**Pull request by romainfrancois**
Using `data$.` might not work in future versions of `dplyr`, using `.` is safer here.

### CODE REVIEW

**Comment by jwildfire** [comment]
Thanks for the PR, @romainfrancois! We'll hold off merging changes until you all decide on the PR.

**Comment by romainfrancois** [comment]
Whatever we decide, .data$. is a bad idea anyway

**Comment by lionel-** [comment]
Agreed that this is not a valid use of the `.data` pronoun, `globalVariables()` is much cleaner and will work in general with magrittr, purrr lambdas, etc.

**Comment by jwildfire** [comment]
👍 👍 

 We'll address in v0.8.0. Filed #173.  Thanks again!

**Pull request merged**
