### PR TITLE
basic profile integration

### LINKED ISSUE #701: Add optional integration of safetyProfile

### PR DESCRIPTION
**Pull request by jwildfire**
# Overview

This PR adds a new tab that shows the `safetyProfile` shiny module as a tab in the safetyGraphics app whenever the `safetyProfile` package is loaded. New functionality includes:

- See participant details in the new "profile" tab
- See the currently selected participant in a new label on the right side of the safetyGraphics application header. 
- Clicking the label opens the profile tab. 
- Use the dropdown in the profile tab to change the selected participant
- Select a participant in a chart to change the selected participant

Note that this update depends on updates to the safetyCharts package that are currently in the `dev` branch (to be released in v0.4)

# Test Code

Checkout this branch and the latest build of safety profile and run: 

```
remotes::install_github("safetyGraphics/safetyCharts@dev")
remotes::install_github("safetyGraphics/safetyProfile@dev")
devtools::install('safetyGraphics')

library(safetyCharts)
library(safetyProfile)
library(safetyGraphics)
safetyGraphicsApp()
```

Test that patProfile is optional:

```
unloadNamespace('safetyProfile')
safetyGraphicsApp() #profile tab should be hidden
library(safetyProfile)
safetyGraphicsApp() #profile tab should be shown
```

### CODE REVIEW

**Comment by jwildfire** [comment]
Next steps:
- Add header with selected participant ID
- Trial integration with a chart

**Comment by jwildfire** [comment]
Last step will be to link patProfile to the charts after https://github.com/SafetyGraphics/safetyCharts/issues/125 is ready.

**Comment by samussiah** [comment]
per @jwildfire - make patient profile an optional plugin?

**Comment by jwildfire** [comment]
Added some code to make make the patient profile optional. Tab is shown when `safetyProfile` package is loaded and hidden otherwise. See test code in PR comments.

**Comment by jwildfire** [comment]
@samussiah I think this one is good to merge if you want to mark as approved and merge in `dev`.  LMK if there are any interesting conflicts that I can help with.

**Review by samussiah — APPROVED** [review]
Plugging this in so easily is a testament to modular design.  Love it!

**Pull request merged**
